Repository validator-labs/validator, pull requests merged in 2024-09, with the labels that each got.

#411 chore: bump oci and network plugin versions
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
Labels: size:S, lgtm

#409 chore(main): release 0.1.10
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M, lgtm

#413 chore(main): release 0.1.11
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M
