Repository validator-labs/validator, pull requests merged in 2024-10, with the labels that each got.

#417 chore(main): release 0.1.12
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M, lgtm

#422 feat: frequency annotation helper
  hauler-manifest.yaml
  pkg/constants/constants.go
  pkg/plugins/plugin_frequency.go
  pkg/plugins/plugin_frequency_test.go
Labels: enhancement, size:M, lgtm

#436 chore: Update renovate.json
  renovate.json
Labels: size:XS, lgtm
