Repository validator-labs/validator, pull requests merged in 2024-07, with the labels that each got.

#305 chore(main): release 0.0.44
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
Labels: autorelease: pending

#321 chore(main): release 0.0.45
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:S

#322 feat: air-gapped support with Hauler
  api/v1alpha1/validatorconfig_types.go
  config/crd/bases/validation.spectrocloud.labs_validatorconfigs.yaml
  go.mod
  go.sum
  internal/controller/validatorconfig_controller.go
  pkg/oci/oci_client.go
  pkg/util/file.go
Labels: enhancement, size:L, lgtm

#324 chore(main): release 0.0.46
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
Labels: enhancement, autorelease: pending, size:S

#326 docs: recommend validatorctl; document Hauler
  README.md
Labels: documentation, size:M

#334 chore: move string utils to central location
  internal/utils/strings/strings.go
  internal/utils/strings/strings_test.go
Labels: size:L, lgtm

#335 fix: make string utils avail externally
  pkg/util/strings.go
  pkg/util/strings_test.go
Labels: size:XS, lgtm

#327 chore(main): release 0.0.47
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hack/update-versions.sh
  hauler-manifest.yaml
  release-please-config.json
Labels: documentation, autorelease: pending, size:M

#341 fix: sink HTTP clients to read proxy config from environment
  internal/sinks/alertmanager.go
  internal/sinks/sink.go
Labels: bug, size:XS, lgtm

#340 chore(main): release 0.0.48
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M

#342 fix: ensure vsphere password is quoted
  chart/validator/templates/plugin-secret-vsphere.yaml
Labels: bug, size:XS, lgtm

#343 chore(main): release 0.0.49
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: bug, autorelease: pending, size:S, lgtm

#346 chore: bump network plugin versions
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
Labels: bug, size:S, lgtm

#348 chore(main): release 0.0.50
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:S, lgtm

#355 chore: bump all plugin versions with releases
  chart/validator/README.md
  chart/validator/values.yaml
  go.mod
  go.sum
  hauler-manifest.yaml
Labels: size:M, lgtm

#354 chore(main): release 0.0.50
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:S, lgtm

#356 refactor: create root level HelmConfig struct which applies to all HelmReleases
  Makefile
  api/v1alpha1/validatorconfig_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  chart/validator/README.md
  chart/validator/crds/validation.spectrocloud.labs_validationresults.yaml
  chart/validator/crds/validation.spectrocloud.labs_validatorconfigs.yaml
  chart/validator/templates/validator-config.yaml
  chart/validator/values.yaml
  config/crd/bases/validation.spectrocloud.labs_validatorconfigs.yaml
  hack/chart/values-base.yaml
  hack/update-versions.sh
  hauler-manifest.yaml
  internal/controller/testdata/vc-network.yaml
  internal/controller/validatorconfig_controller.go
  internal/controller/validatorconfig_controller_test.go
  pkg/helm/helm.go
  pkg/helm/options.go
Labels: enhancement, size:L, lgtm
