Repository validator-labs/validator, pull requests merged in 2024-08, with the labels that each got.

#363 chore(main): release 0.1.0
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: bug, autorelease: pending, size:M, lgtm, new-feature

#364 feat: add values for maas plugin
  chart/validator/README.md
  chart/validator/templates/plugin-secret-maas.yaml
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hauler-manifest.yaml
Labels: size:M, lgtm, new-feature

#366 refactor: expose sinks pkg for direct rule evaluation; add ValidationResult creation & finalization helpers
  cmd/main.go
  internal/controller/suite_test.go
  internal/controller/validationresult_controller.go
  internal/controller/validatorconfig_controller_test.go
  pkg/kube/kube.go
  pkg/sinks/alertmanager.go
  pkg/sinks/alertmanager_test.go
  pkg/sinks/sink.go
  pkg/sinks/sink_test.go
  pkg/sinks/slack.go
  pkg/test/controller_runtime_client.go
  pkg/test/controller_runtime_patchhelper.go
  pkg/validationresult/validation_result.go
  pkg/validationresult/validation_result_test.go
Labels: size:L

#367 feat: HTTP basic authentication secrets for network plugin
  chart/validator/README.md
  chart/validator/templates/plugin-secret-network-auth.yaml
  chart/validator/values.yaml
  hack/chart/values-base.yaml
Labels: size:L, new-feature

#365 chore(main): release 0.1.1
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M

#374 fix: ensure validatorctl arch matches haul arch
  Makefile
  chart/validator/README.md
  chart/validator/values.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: bug, size:S

#378 docs: update architecture diagram
  README.md
  docs/img/validator.png
Labels: size:S

#379 feat: add GroupResource consts; set TypeMeta in Build
  api/v1alpha1/groupversion_info.go
  pkg/validationresult/validation_result.go
Labels: enhancement, size:M

#381 chore: bump oci plugin version
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
Labels: size:S, lgtm

#377 chore(main): release 0.1.3
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M, lgtm

#385 chore: bump plugin versions
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
Labels: size:M, lgtm

#386 chore(main): release 0.1.4
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M, lgtm

#391 chore(main): release 0.1.5
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: bug, autorelease: pending, size:M, lgtm

#395 chore: bump plugin versions
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
Labels: size:S, lgtm

#394 chore(main): release 0.1.6
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M, lgtm

#399 refactor: new validation rule interface
  hauler-manifest.yaml
  pkg/validationresult/validation_result.go
  pkg/validationrule/validation_rule.go
Labels: size:M, lgtm

#400 chore(main): release 0.1.7
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:S

#403 feat: introduce PluginSpec interface
  chart/validator/README.md
  chart/validator/values.yaml
  hauler-manifest.yaml
  pkg/plugins/plugins.go
Labels: size:M, lgtm, new-feature

#402 chore(main): release 0.1.8
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M, lgtm

#404 chore(main): release 0.1.9
  .release-please-manifest.json
  CHANGELOG.md
  chart/validator/Chart.yaml
  chart/validator/README.md
  chart/validator/values.yaml
  hack/chart/values-base.yaml
  hack/hauler-manifest-template.yaml
  hauler-manifest.yaml
Labels: autorelease: pending, size:M, lgtm
